### PR TITLE
Refresh link tracking whenever new link appear in the app

### PR DESCRIPTION
**Pull request by joe-miskolczy**
This is a 2nd run for this change. This time I avoided modifying the DOM tapping into event bubbling on the document.body level. I also took care of refreshing link tracking whenever we get new Algolia search results but the price was a full eject swizzle. Might worth discussing if we really want to go down that route.

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by joe-miskolczy** [comment]
@snowplowcla  I just signed the company internal one.

**Review by matus-tomlein — APPROVED** [review]
LGTM! It's unfortunate how much trouble it is to implement refreshing the link click tracking. Perhaps we should revisit if there is a different way to refresh it in the tracker.

**Comment by joe-miskolczy** [comment]
@matus-tomlein I agree 100%, it's especially painful in SPAs. An initial idea could be to attack a MutationObserver and look for new "a" elements appearing then automatically calling the refresh code.

**Pull request merged**
