### PR TITLE
docs: typo

### PR DESCRIPTION
**Pull request by vitaliytv**
space https://docs.snowplow.io/docs/getting-started-on-snowplow-open-source/setup-snowplow-on-gcp/setup-trackers/

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by vitaliytv** [comment]
I signed it!

**Comment by snowplowcla** [comment]
Confirmed! @vitaliytv has signed the Contributor License Agreement. Thanks so much.

**Review by rlh1994 — APPROVED** [review]
Thanks for catching this!

**Pull request merged**
