### PR TITLE
Update statement-of-support.md

### PR DESCRIPTION
**Pull request by charlotte-at-snowplow**
v 2.0.1 Added severity level definitions and minor edits

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by charlotte-at-snowplow** [comment]
Snowplow Contributor License Agreement Exclusion v1.0
Your response has been recorded

**Comment by snowplowcla** [comment]
Confirmed! @charlotte-at-snowplow has signed the Contributor License Agreement. Thanks so much.

**Comment by charlotte-at-snowplow** [comment]
I signed it!

**Review by georgekoliop — APPROVED** [review]

**Pull request merged**
