### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by danielyyy4**
Updated the info section to make it more aligned to our new Packaging and Pricing. This was also a request I already review and got approval from Michele.

### CODE REVIEW

**Comment by snowplowcla** [comment]
Confirmed! @danielyyy4 has signed the Contributor License Agreement. Thanks so much.

**Comment by danielyyy4** [comment]
@johnmicahreid  could you help with this request please!

**Comment by johnmicahreid** [comment]
@danielyyy4 just a note that you should add someone as a reviewer to ensure that your contributions get merged. 

At this level, the wording should be DBT packages, not DBT models, otherwise we will confuse our audience and make the product seem smaller than it is. A package contains multiple models, and we make efforts to ensure that we always talk about the Unified Digital DBT package / Media package etc.

**Review by johnmicahreid — APPROVED** [review]
Approved, conditional on changing the wording to packages rather than models.

**Comment by danielyyy4** [comment]
That makes sense, thanks for catching @johnmicahreid

**Pull request merged**
